name: Pull request check

on:
  pull_request:
    branches:
      - master

jobs:
  pull_request_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile --ignore-engines
      - name: Danger JS Action
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
